"""add_cascade_delete

Revision ID: b667d665d725
Revises: 64caf03b211a
Create Date: 2026-01-09 12:30:56.326847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b667d665d725'
down_revision: Union[str, Sequence[str], None] = '64caf03b211a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alerts_service_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('check_results_service_id_fkey'), 'check_results', type_='foreignkey')
    op.create_foreign_key(None, 'check_results', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'check_results', type_='foreignkey')
    op.create_foreign_key(op.f('check_results_service_id_fkey'), 'check_results', 'services', ['service_id'], ['id'])
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_service_id_fkey'), 'alerts', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###
