"""add_sent_to_alerts

Revision ID: f00d67185f1e
Revises: b667d665d725
Create Date: 2026-01-09 15:51:10.984659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00d67185f1e'
down_revision: Union[str, Sequence[str], None] = 'b667d665d725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'sent')
    # ### end Alembic commands ###
